### ISSUE TITLE
datGui example not working on firefox and safari

### ISSUE THREAD

**Issue by fx-lange** [fx-lange/ofxSyncedParams#9]
starting the example-html gives me:
in firefox (39):
`ReferenceError: MozWebSocket is not defined`
in Safari:
`WebSocket network error: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.)`

**Comment by fx-lange** [comment]
@inx, it should work on chrome (as a quick solution)

**Comment by i-n-g-o** [comment]
hi.

i can confirm it works in ff, chrome and safari now.
thanks! (inx)
